LeorElla/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('dashboard/',views.dashboard,name='dashboard'),
   
   
    path('logout/',views.logout,name='logout'),
    path('error/',views.Errorpage,name='errorpage'),
    path('contactus/',views.ContactUs,name='contactus'),
    path('bagcategory/',views.bagcategory,name='bagcategory'),
    path('dresscategory/',views.dresscategory,name='dresscategory'),
    path('footwearcategory/',views.footwearcategory,name='footwearcategory'),
    path('cart/',views.cart,name='cart'),
    path('payment/',views.payment,name='payment'),
    path('add_to_cart/<int:p_id>',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>',views.remove_from_cart,name='remove_from_cart'),
    path('wishlist/',views.wish,name='wishlist'),
    path('add_wishlist/<int:pid>',views.add_wishlist,name='add_wishlist'),
    path('remove_from_wish/<int:product_id>',views.remove_from_wish,name='remove_from_wish'),
]

seller/urls.py
from django.urls import path
from.import views
app_name='seller'
urlpatterns=[
    path('',views.home),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('sellerdashboard/',views.sellerdashboard,name='sellerdashboard'),
    path('addpdt/',views.addpdt,name='addpdt'),
    path('viewpdt/',views.viewpdt,name='viewpdt'),
    path('updatepdt/<int:pid>',views.updatepdt,name='updatepdt'),
    path('deletepdt/<int:pid>',views.deletepdt,name='deletepdt'),
    path('logout/',views.logout,name='logout'),
    path('category',views.category,name='category'),
    path('viewcat/',views.viewcat,name='viewcat'),
    path('updatecat/<int:cat>',views.updatecat,name='updatecat'),
    path('deletecat/<int:cid>',views.deletecat,name='deletecat')


]
    

customer/models.py
from django.db import models
from seller.models import Product
# Create your models here.
class Customer(models.Model):
    name=models.TextField(max_length=100,null=True)
    email=models.TextField(max_length=100,null=True)
    mob=models.PositiveIntegerField(null=True)
    password=models.TextField(max_length=100,null=True)
    def __str__(self):
        return self.name


class Contactus(models.Model):
    name=models.TextField(max_length=100,null=True)
    email=models.TextField(max_length=100,null=True)
    yourmessage=models.TextField(max_length=100,null=True)

class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveIntegerField(default=1)

class Wishlist(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    quantity=models.PositiveIntegerField(default=1)

customer/views.py
from django.shortcuts import render,redirect
from .models import *
from seller.models import *
# Create your views here.
def home(request):
    return render(request,'customer/home.html')

def signup(request):
    if request.method=='POST':
        namee=request.POST['name']
        emaill=request.POST['email']
        num=request.POST['number']
        pswd=request.POST['password']
        Cus=Customer(name=namee,email=emaill,mob=num,password=pswd)
        Cus.save()
    return render(request,'customer/signup.html')

def login(request):
    if request.method=='POST':
        email=request.POST['email']
        pswd=request.POST['password']
        try:
         customer=Customer.objects.get(email=email,password=pswd)
         request.session['customer']=customer.id
         return redirect('customer:dashboard')
        except Customer.DoesNotExist:
          return render(request,'customer/login.html',{'msg':'invalid username or password'})
    # if Customer.objects.filter(email=email,password=pswd).exists():
    #     return redirect('customer:dashboard')
    # else:
    #     return render(request,'customer/login.html',{'msg':'invalid email and pswd'})

    return render(request,'customer/login.html')
def dashboard(request):
    if 'customer' in request.session:
        return render(request,'customer/dashboard.html')
    else:
        return render(request,'customer/errorpage.html')








def logout(request):
    if 'customer' in request.session:
        del request.session['customer']
        return redirect('customer:home')
    
def Errorpage(request):
    return render(request,'customer/errorpage.html')
def ContactUs(request):
    if request.method=='POST':
        namee=request.POST['name']
        emaill=request.POST['email']
        msg=request.POST['yourmessage']
        Cus=Contactus(name=namee,email=emaill,yourmessage=msg,)
        Cus.save()
    return render(request,'customer/contactus.html')

def bagcategory(request):
    bag=Category.objects.get(c_name='BAG')
    pdt=Product.objects.filter(category=bag)
    return render(request,'customer/bagcategory.html',{'products':pdt})
def dresscategory(request):
    drs=Category.objects.get(c_name='DRESS')
    pdt=Product.objects.filter(category=drs)
    return render(request,'customer/dresscategory.html',{'products':pdt})

def footwearcategory(request):
    foot=Category.objects.get(c_name='FOOTWEAR')
    pdt=Product.objects.filter(category=foot)
    return render(request,'customer/footwearcategory.html',{'products':pdt})

def cart(request):
    cartitems =Cart.objects.all()
    total_price=sum(item.product.p_price*item.quantity for item in cartitems)
    total_price_per_item=[]
    grand_total=0
    for item in cartitems:
        item_total=item.product.p_price*item.quantity
        total_price_per_item.append({'item':'item_total'})
        grand_total+=item_total
    return render(request,'customer/cart.html',{'cartitems':cartitems,'grand_total':grand_total,'total_price':total_price})
def payment(request):
    return render(request,'customer/payment.html')
def add_to_cart(request,p_id):
    if request.method=='POST':
        product=Product.objects.get(id=p_id)
        cart_item,created=Cart.objects.get_or_create(product=product)
        if not created:
            cart_item.quantity+=1
            cart_item.save()
    return redirect('customer:cart')
def remove_from_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    cart_item=Cart.objects.get(product=product)
    cart_item.delete()
    return redirect('customer:cart')

def wish(request):
    wish =Wishlist.objects.all()
    total_price=sum(item.product.p_price for item in wish)
    total_price_per_item=[]
    grand_total=0
    for item in wish:
        item_total=item.product.p_price
        total_price_per_item.append({'item':'item_total'})
        grand_total+=item_total
    return render(request,'customer/wishlist.html',{'wishlist':wish,'grand_total':grand_total,'total_price':total_price})

def add_wishlist(request,pid):
    if request.method=='POST':
        product=Product.objects.get(id=pid)
        wishlist,created=Wishlist.objects.get_or_create(product=product)
        if not created:
            wishlist.quantity+=1
            wishlist.save()
    return redirect('customer:wishlist')

def remove_from_wish(request,product_id):
    product=Product.objects.get(id=product_id)
    wishlist=Wishlist.objects.get(product=product)
    wishlist.delete()
    return redirect('customer:wishlist')

customer/templates/customer/bagcategory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/w3css/3/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <h3>LeorElla</h3>
              <!-- <a href="signup"><img src="image/download.png" alt=""></a> -->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  
                  <li><a class="dropdown-item"href=" ">Log Out</a></li>
                  <li><a class="dropdown-item" href="{% url 'customer:contactus' %}">Contact Us</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:login' %}">Seller Login</a></li>
                 
                  
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Dresses</a></li>
                    <li><a class="dropdown-item" href="#">Hand Bags</a></li>
                    <li><a class="dropdown-item" href="#">Footwears</a></li>
                    
                  </ul>
                </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:login' %}">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"> My Cart</a>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <div class="row">
            {% for i in products %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{i.p_image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{i.p_name}}</h5>
                      <p class="card-text">{{i.p_price}}</p>
                     <form action="{% url 'customer:add_to_cart' i.id %}" method="post">
                      
                      {% csrf_token %}
                      <div class="quantity" style="display: none;">
                        <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                      </div>
                      <button type="submit" class="btn btn-light" style="width:150px; margin-top:0px; margin-left: 100px;">Add To Cart</button>
                     </form>
                     <form action="{% url 'customer:add_wishlist' i.id %}" method="post">
                      
                      {% csrf_token %}
                      <div class="quantity" style="display: none;">
                        <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                      </div>
                      <button type="submit" class="btn btn-light" style="width:150px; margin-top:0px; margin-left: 100px;">Wishlist</button>
                     </form>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
      </div>
</body>
</html>

customer/templates/customer/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>
<body style="background-image:url('https://i.pinimg.com/236x/7a/cf/05/7acf05bde65f33452c0306982de1251e.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-4 hello"></div>
          
  
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <h3>LeorElla</h3>
              <!-- <a href="signup"><img src="image/download.png" alt=""></a> -->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  
                  <li><a class="dropdown-item"href=" ">Log Out</a></li>
                  <li><a class="dropdown-item" href="{% url 'customer:contactus' %}">Contact Us</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:login' %}">Seller Log In</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:signup' %}">Seller Sign Up</a></li>
                  
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'customer:dresscategory' %}">Dresses</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:bagcategory' %}">Hand Bags</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:footwearcategory' %}">Footwears</a></li>
                    
                  </ul>
                </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:login' %}">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:cart' %}"> My Cart</a>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav> 

<h1>Add To Cart</h1>
<!-- <table>
    <tr>
        <td>name</td>
        <td>image</td>
        <td>price</td>
    </tr>
</table> -->
<table>
  <tr>
    <th>produts</th>
    <th>price<th>
      <th>quantity</th>
  </tr>
  {% for i in cartitems %}
  <tr>
    <td><img src="{{i.product.p_image.url}}" alt="" width="50px"></td>
    <td><p>{{i.product.p_price}}</p></td>
    <td><p>{{i.quantity}}</p></td>
    <td>
      <form action="{% url 'customer:remove_from_cart' i.product.id %}" method="post">
        {% csrf_token %}
        <button type="submit" style="color: rgb(25, 26, 27); border-radius: 10px;">delete</button>
      </form>
    </td>
   
  </tr>
  {% endfor %}
 </table>


<div class="container">
  <div class="row">
      <div class="col-4 ">
        <button type="button" class="btn btn-secondary"> <a href="{% url 'customer:payment' %}">Buy Now</a></button>
        <button type="button" class="btn btn-outline-secondary"> <a href="{% url 'customer:wishlist' %}">Save TO Wishlist</a></button>
       
      
      </div>
      

      <script src="{% static 'js/cart.js' %}"></script>     
      <div class="roll">   
      <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      </div> 
</body>
</html>

customer/templates/customer/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        table{
            border-bottom: 1px solid black;
            width: 100%;
        }
        table td h1 a{
           text-decoration: none;
        }
    </style>
</head>
<body style="background-image:url('https://i.pinimg.com/236x/b9/ed/3c/b9ed3c2a1dc761e6a1044e1840c9b6ce.jpg')">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <h3>LeorElla</h3>
              <!-- <a href="signup"><img src="image/download.png" alt=""></a> -->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  
                  <li><a class="dropdown-item"href=" ">Log Out</a></li>
                  <li><a class="dropdown-item" href="{% url 'customer:contactus' %}">Contact Us</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:login' %}">Seller Log In</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:signup' %}">Seller Sign Up</a></li>
                  
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'customer:dresscategory' %}">Dresses</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:bagcategory' %}">Hand Bags</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:footwearcategory' %}">Footwears</a></li>
                    
                  </ul>
                </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:login' %}">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:cart' %}"> My Cart</a>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav> 

    <div class="container">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'image/23.jpg' %}" alt="Card image cap" height="350px">
                <div class="card-body">
                  <h5 class="card-title"></h5>
                  <p class="card-text"><h1><a href="{% url 'customer:dresscategory' %}">dresses</a></h1></p>
                 
                  
                </div>
              </div>
            </div>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'image/22.jpg' %}" alt="Card image cap" height="350px">
                <div class="card-body">
                  <h5 class="card-title"></h5>
                  <p class="card-text"><h1><a href="{% url 'customer:bagcategory' %}">bags</a></h1></p>
                 
                  
                </div>
              </div>
            </div>
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'image/foot22.jpg' %}"alt="Card image cap" height="350px">
                <div class="card-body">
                  <h5 class="card-title"></h5>
                  <p class="card-text"><h1><a href="{% url 'customer:footwearcategory' %}">foot wear</a></h1></p>
                 
                  
                </div>
              </div>
            </div>
        </div>
    </div>
   
    

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

customer/templates/customer/wishlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/wishlist.css' %}">
</head>
<body style="background-image:url('https://i.pinimg.com/236x/b3/53/3a/b3533a11ac214b30bb50f8d88c288ce3.jpg')">
  <div class="container">
      <div class="row">
          <div class="col-4 hello"></div>
          
  
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <h3>LeorElla</h3>
              <!-- <a href="signup"><img src="image/download.png" alt=""></a> -->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  
                  <li><a class="dropdown-item"href=" ">Log Out</a></li>
                  <li><a class="dropdown-item" href="{% url 'customer:contactus' %}">Contact Us</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:login' %}">Seller Log In</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:signup' %}">Seller Sign Up</a></li>
                  
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
                </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'customer:dresscategory' %}">Dresses</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:bagcategory' %}">Hand Bags</a></li>
                    <li><a class="dropdown-item" href="{% url 'customer:footwearcategory' %}">Footwears</a></li>
                    
                  </ul>
                </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:wishlist' %}">Wish List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:login' %}">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'customer:cart' %}"> My Cart</a>
              </li>
              
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav> 

<h1>Wishlist</h1>
<!-- <table>
    <tr>
        <td>name</td>
        <td>image</td>
        <td>price</td>
    </tr>
</table> -->
<table>
  <tr>
    <th>produts</th>
    <th>price<th>
       
        
  </tr>
  {% for i in wishlist %}
  <tr>
    <td><img src="{{i.product.p_image.url}}" alt="" width="50px"></td>
    <td><p>{{i.product.p_price}}</p></td>
    <td>
        <form action="{% url 'customer:remove_from_wish' i.product.id %}" method="post">
          {% csrf_token %}
          <button type="submit" style="color: rgb(25, 26, 27); border-radius: 10px;">remove</button>
        </form>
      </td>
    
    
     
   
  </tr>
  {% endfor %}
 </table>


<div class="container">
  <div class="row">
      <div class="col-4 ">
        <button type="button" class="btn btn-secondary"><a href="{% url 'customer:payment' %}">Buy Now</a></button>
        <button type="button" class="btn btn-outline-secondary"><a href="{% url 'customer:cart' %}">Add To Cart</a></button>
       
      
      </div>
      

      <script src="{% static 'js/wishlist.js' %}"></script>     
      <div class="roll">   
      <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      </div> 
</body>
</html>