LeorElla/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('seller/',include('seller.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from.import views
app_name='customer'
urlpatterns=[
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('dashboard/',views.dashboard,name='dashboard'),
   
   
    path('logout/',views.logout,name='logout'),
    path('error/',views.Errorpage,name='errorpage'),
    path('contactus/',views.ContactUs,name='contactus'),
    path('bagcategory/',views.bagcategory,name='bagcategory'),
    path('dresscategory/',views.dresscategory,name='dresscategory'),
    path('footwearcategory/',views.footwearcategory,name='footwearcategory'),
    path('cart/',views.cart,name='cart'),
    path('payment/',views.payment,name='payment'),
    path('add_to_cart/<int:p_id>',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>',views.remove_from_cart,name='remove_from_cart'),
    path('wishlist/',views.wish,name='wishlist'),
    path('add_wishlist/<int:pid>',views.add_wishlist,name='add_wishlist'),
    path('remove_from_wish/<int:product_id>',views.remove_from_wish,name='remove_from_wish'),
]

seller/urls.py
from django.urls import path
from.import views
app_name='seller'
urlpatterns=[
    path('',views.home),
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('sellerdashboard/',views.sellerdashboard,name='sellerdashboard'),
    path('addpdt/',views.addpdt,name='addpdt'),
    path('viewpdt/',views.viewpdt,name='viewpdt'),
    path('updatepdt/<int:pid>',views.updatepdt,name='updatepdt'),
    path('deletepdt/<int:pid>',views.deletepdt,name='deletepdt'),
    path('logout/',views.logout,name='logout'),
    path('category',views.category,name='category'),
    path('viewcat/',views.viewcat,name='viewcat'),
    path('updatecat/<int:cat>',views.updatecat,name='updatecat'),
    path('deletecat/<int:cid>',views.deletecat,name='deletecat')


]
    

seller/models.py
from django.db import models

# Create your models here.
class Seller(models.Model):
    name=models.TextField(max_length=100,null=True)
    email=models.TextField(max_length=100,null=True)
    mob=models.PositiveIntegerField(null=True)
    password=models.TextField(max_length=100,null=True)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table='seller'
class Category(models.Model):
    c_name=models.TextField(max_length=50,null=True,db_column='name')
    c_image=models.ImageField(upload_to='category',null=True,db_column="image")
    c_description=models.TextField(max_length=200,null=True,db_column='description')
    def __str__(self):
        return self.c_name
    class Meta:
        db_table='category'
    
class Product(models.Model):
    p_name=models.TextField(max_length=50,null=True,db_column='name')
    p_image=models.ImageField(upload_to='produts',null=True,db_column="image")
    p_price=models.PositiveIntegerField(null=True,db_column='price')
    p_description=models.TextField(max_length=200,null=True,db_column='description')
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.p_name
    class Meta:
        db_table='product'

seller/views.py
from django.shortcuts import render,redirect
from . models import *
# Create your views here.
def home(request):
    return render(request,'seller/home.html')
def signup(request):
    if request.method=='POST':
        namee=request.POST['name']
        emaill=request.POST['email']
        num=request.POST['number']
        pswd=request.POST['password']
        Sell=Seller(name=namee,email=emaill,mob=num,password=pswd)
        Sell.save()
        return redirect('seller:login')
    return render(request,'seller/signup.html')
def login(request):
    if request.method=='POST':
        email=request.POST['email']
        pswd=request.POST['password']
        try:
            seller=Seller.objects.get(email=email,password=pswd)
            request.session['seller']=seller.id
            return redirect('seller:sellerdashboard')
        except Seller.DoesNotExist:
            return render(request,'seller/login.html',{'msg':'invalid username or password'})
        # if Seller.objects.filter(email=email,password=pswd).exists():
        #     return redirect('seller:sellerdashboard')
        # else:
        #     return render(request,'seller/login.html',{'msg':'invalid mail and pswd'})
    return render(request,'seller/login.html')
def sellerdashboard(request):
    if 'seller' in request.session:
        return render(request,'seller/sellerdashboard.html')
    else:
        return render(request,'seller/errorpage.html')
def addpdt(request):
    cat=Category.objects.all()
    if request.method=='POST':
        name=request.POST['name']
        price=request.POST['price']
        description=request.POST['description']
        image=request.FILES['image']
        cat=request.POST.get('cat')
        category=Category.objects.get(pk=cat)
        pdt=Product(p_name=name,p_price=price,p_image=image,category=category,p_description=description)
        pdt.save()
        return render(request,'seller/addproduct.html')
    return render(request,'seller/addproduct.html',{'cat':cat})

def viewpdt(request):
    pdts=Product.objects.all()
    return render(request,'seller/viewpdt.html',{'products':pdts})

def updatepdt(request,pid):
    pdt=Product.objects.get(id=pid)
    if request.method=='POST':
        name=request.POST['name']
        price=request.POST['price']
        description=request.POST['description']

    #update
        pdt.p_name=name
        pdt.p_price=price
        pdt.p_description=description
        pdt.save()
        return redirect('seller:viewpdt')
    return render(request,'seller/updatepdt.html',{'pdt':pdt})
                  
def deletepdt(request,pid):
    Pdt=Product.objects.get(id=pid).delete()
    return redirect('seller:viewpdt')


def logout(request):
    if 'seller' in request.session:
        del request.session['seller']
        return redirect('seller:home')
    
def category(request):
    if request.method=='POST':
        name=request.POST['name']
        description=request.POST['description']
        image=request.FILES['image']
        category=Category(c_name=name,c_image=image,c_description=description)
        category.save()
        return redirect('seller:sellerdashboard')
    return render(request,'seller/addcat.html')

def viewcat(request):
    category=Category.objects.all()
    return render(request,'seller/viewcat.html',{'category':category})

def updatecat(request,cat):
    category=Category.objects.get(id=cat)
    if request.method=='POST':
        name=request.POST['name']
        description=request.POST['description']
        category.c_name=name
        category.c_description=description
        category.save()
        return redirect('seller:viewcat')
    return render(request,'seller/updatecat.html',{'category':category})
def deletecat(request,cid):
    cat=Category.objects.get(id=cid).delete()
    return redirect('seller:viewcat')

seller/templates/seller/addcat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
</head>
<body style="background-image:url('https://i.pinimg.com/236x/86/42/ba/8642ba096b248b61c318a0465757cf16.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-4 hello"></div>
            <div class="col-4 category" style="background-image: url('https://i.pinimg.com/236x/0c/32/20/0c3220f3a764b4629be937f81ada2cda.jpg');">
    
    <h6>   <a href="{% url 'seller:logout' %}">LogOut</a></h6>

    <h1>category</h1>
    <form action="" onsubmit="return po()" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
    <tr>
        <td><label for="">category Name</label></td>
        <td><input type="text" name="name" id=""> <br></td>
    </tr>
    <tr>
        <td><label for="">category image</label></td>
        <td><input type="file" name="image" id=""><br></td>
    </tr>
    <tr>
        <td><label for="">category Description</label></td>
        <td> <input type="text" name="description" id="description"></td>
    </tr>
    <tr>
        <td><p id="pa" style="color: brown;"></p></td>
        <td><input type="submit" value="submit"></td>
    </tr>
    </table>
    </form>
    <script src="{% static 'js/category.js' %}"></script>     
<div class="roll">   
<script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</div> 
</body>
</html>

seller/templates/seller/addproduct.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/addproduct.css' %}">
    <style>
        h1{
            text-align: center;
        }
    </style>
</head>
<body style="background-image:url('https://i.pinimg.com/236x/39/aa/02/39aa02dc615f6e516a6e0dd522583eac.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-4 hello"></div>
            <div class="col-4 signup" style="background-image: url('https://i.pinimg.com/236x/91/8d/2b/918d2b756bd490820787a92929de7576.jpg');">
    
    <h6>   <a href="{% url 'seller:logout' %}">LogOut</a></h6>

    <h1>Product</h1>
    <form action="" onsubmit="return po()" method="post" enctype="multipart/form-data">
        
        {% csrf_token %}
        <table>
            <tr>
        <td><label for="">Product Name</label></td>
        <td><input type="text" name="name" id=""> <br><br></td>
    </tr>
    <tr>
        <td><label for="">product image</label></td>
        <td> <input type="file" name="image" id=""><br></td>
    </tr>
    <tr>
        <td><label for="">Product Price</label></td>
        <td><input type="number" name="price" id=""> <br><br></td>
    </tr>
    <tr>
        <td><label for="">Product Description</label></td>
        <td><input type="text" name="description" id="description"></td>
    </tr>
        <tr>
        </table>
            <label for="">category</label>
        
            v<select name="cat" id="">
            {% for i in cat %}
            <option value="{{i.id}}">{{i.c_name}}</option>
            {% endfor %}
        </select>
         <p id="pa" style="color: brown;"></p>
         <input type="submit" value="submit">
    
    
    </form>
</body>
</html>

seller/templates/seller/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>   <a href="{% url 'seller:logout' %}">LogOut</a></h2>

    <h1>category</h1>
    <form action="" onsubmit="return po()" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="">category Name</label>
        <input type="text" name="name" id=""> <br><br>
        <label for="">category image</label>
        <input type="file" name="image" id=""><br>
        <label for="">category Description</label>
        <input type="text" name="description" id="description">
        <p id="pa" style="color: brown;"></p>
        <input type="submit" value="submit">
    </form>
</body>
</html>

seller/templates/seller/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <style>
       
       .login{
        box-shadow: 2px 3px 4px rgb(167, 158, 158);
       }
       .login h1{
        text-align: center;
       }
       .mgbtn{
        margin-left: 100px;
       }
      

    </style>
</head>
<body style="background-image:url('https://i.pinimg.com/236x/ce/85/7a/ce857aeeedf9046b3a3fdc9241ee05a9.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-4 hello"></div>
            <div class="col-4 login" style="background-image: url('https://i.pinimg.com/236x/e3/f2/6a/e3f26ad2802ee8682a5fcbffcfbb0267.jpg');">
    
    <h6>   <a href="{% url 'seller:logout' %}">LogOut</a></h6>
    <!-- <h2><a href="{% url 'seller:signup' %}">create account</a></h2> -->
    <h1>login page</h1>
  
    <form action="" onsubmit="return po()" method="post">
        {% csrf_token %}
        <table>
            <tr>
            <td><label for="">email</label></td>
            <td><input type="text " name="email" id="email"></td>
            </tr>
            <br>
            <tr>
            <td><label for="">password</label></td>
            <td><input type="password" name="password" id="password"></td>
            </tr> 
            <p id="pa" style="color: brown;">{{msg}}</p>
        
            <tr>
                <td colspan="2">
                    <button type="submit" class="btn btn-secondary mgbtn">Submit</button>
                </td>
            </tr>
          
    </form>
    
         </div>
         <div class="col-4"></div>
     </div>
  
</div>
<script src="{% static 'js/login.js' %}"></script>     
<div class="roll">   
<script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</div> 
</body>
</html>

seller/templates/seller/sellerdashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table{
            border-bottom: 1px solid black;
            width: 100%;
        }
        table td h1 a{
           text-decoration: none;
        }
    </style>
</head>
<body style="background-image:url('https://i.pinimg.com/236x/67/39/c5/6739c51ccaab206326008e5c1fc1d3c5.jpg')">
    <div class="container">
        <div class="row">
    <h6>   <a href="{% url 'seller:logout' %}">LogOut</a></h6>

    <table>
        <tr>
            <td><h1><a href="{% url 'seller:addpdt' %}">Add Product</a></h1></td>
            
            <td><h1><a href="{% url 'seller:viewpdt' %}">View Products</a></h1></td>

            <td><h1><a href="{% url 'seller:category' %}">Add cat</a></h1></td>
            
            <td><h1><a href="{% url 'seller:viewcat' %}">View cat</a></h1></td>

           
        </tr>
    </table>
</body>
</html>

seller/templates/seller/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
<body>
    <body style="background-image:url('https://i.pinimg.com/236x/0b/b4/1c/0bb41cdf62e68c56c3cbd227a5ca517c.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-4 hello"></div>
                <div class="col-4 signup" style="background-image: url('https://i.pinimg.com/236x/74/ae/f3/74aef349070f64389d7047283a877306.jpg');">
        
</head>
<body>
    <h1>signup</h1>
    <form action="" onsubmit="return po()" method="post">
        {% csrf_token %}
        <table>
        <tr>
        <td><label for="">name</label></td>
        <td><input type="text" name="name" id="name"></td>
        <br>
        </tr>
        <tr>
        <td> <label for="">email</label></td>
        <td><input type="text " name="email" id="email"></td>
        <br>
        </tr>
        <tr>
        <td> <label for="">number</label></td>
        <td><input type="text" name="number" id="number"></td>
        <br>
        </tr>
        <tr>
        <td> <label for="">password</label></td>
        <td><input type="password" name="password" id="password"></td>
        <br>
        </tr>
        <tr>
        <td> <label for="">comform password</label></td>
        <td><input type="password" name="" id="comformpassword"></td>
        </tr>
        <p id="pa" style="color: brown;"></p>
        <tr>
         <td><input type="submit" value="submit"></td>
        </tr>
        
    </table>
    <script src="{% static 'js/signup.js' %}"></script>     
    <div class="roll">   
    <script src="	https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </div> 
    
</body>
</html>

seller/templates/seller/updatecat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>   <a href="{% url 'seller:logout' %}">LogOut</a></h2>

    <h1>category</h1>
    <form action="" onsubmit="return po()" method="post">
        {% csrf_token %}
        
        <label for="">category Name</label>
        <input type="text" name="name" id="" value="{{category.c_name}}"> <br><br>
        <label for="">category Description</label>
        <input type="text" name="description" id="description" value="{{category.c_description}}">
        <p id="pa" style="color: brown;"></p>
        <input type="submit" value="submit">
    </form>
</body>
</html>

seller/templates/seller/updatepdt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>   <a href="{% url 'customer:logout' %}">LogOut</a></h2>

    <h1>Product</h1>
    <form action="" onsubmit="return po()" method="post">
        {% csrf_token %}
        
        <label for="">Product Name</label>
        <input type="text" name="name" id="" value="{{pdt.p_name}}"> <br><br>
        <label for="">Product Price</label>
        <input type="number" name="price" id="" value="{{pdt.p_price}}"> <br><br>
        <label for="">Product Description</label>
        <input type="text" name="description" id="description" value="{{pdt.p_description}}">
        <p id="pa" style="color: brown;"></p>
        <input type="submit" value="submit">
    </form>
</body>
</html>

seller/templates/seller/viewcat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table{
            width: 100%;
        }
        h1{
            text-align: center;
        }
    </style>
</head>
<body  style="background-image:url('https://i.pinimg.com/236x/20/a6/05/20a605e9ded3df20f2e067375ed7b46b.jpg')">
    <div class="container">
        <div class="row">
    <h2>   <a href="{% url 'customer:logout' %}">LogOut</a></h2>

    <table>
        <h1>category</h1>
        <tr>
            <td>name</td>
            <td>description</td>
            <td>image</td>
        </tr>
        {% for i in category %}
        <tr>
            <td>{{i.c_name}}</td>
            <td>{{i.c_description}}</td>
            <td><img src="{{i.c_image.url}}" alt="" width="100px"></td>
            <td><a href="{% url 'seller:updatecat' i.id %}">update</a></td>
            <td><a href="{% url 'seller:deletecat' i.id %}">delete</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

seller/templates/seller/viewpdt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table{
            width: 100%;
        }
        h1{
            text-align: center;
        }
    </style>
</head>
<body style="background-image:url('https://i.pinimg.com/236x/da/9d/62/da9d62e17dc27bf43661857726f236b8.jpg')">
    <div class="container">
        <div class="row">
    <table>
        <h2>   <a href="{% url 'seller:logout' %}">LogOut</a></h2>

        <h1>Product</h1>
        <tr>
            <td>name</td>
            <td>image</td>
            <td>price</td>
            <td>description</td>
            <td>update</td>
            <td>delete</td>
            
        </tr>
        {% for i in products %}
        <tr>
            <td>{{i.p_name}}</td>
            <td><img src="{{i.p_image.url}}" alt="" width="200px" height="200px"></td>
            <td>{{i.p_price}}</td>
            <td>{{i.p_description}}</td>
            <td><a href="{% url 'seller:updatepdt' i.id %}">update</a></td>
            <td><a href="{% url 'seller:deletepdt' i.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>